<!-- <a href="https://colab.research.google.com/github/vkate1/Summer-Training-for-III-year/blob/main/Day6/ANN/Multiclass_Classification_OwnDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> -->

#  Importing packages

In [1]:
from __future__ import print_function
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras import backend as K

import tensorflow as tf

# Preparing Dataset

In [2]:
# Generate dummy data
import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(2, size=(1000, 1))

# Convert labels to categorical one-hot encoding
labels = tf.keras.utils.to_categorical(labels, num_classes=10)

test_data = np.random.random((200, 100))
test_labels = np.random.randint(2, size=(200, 1))
test_labels = tf.keras.utils.to_categorical(test_labels, num_classes=10)

print(test_labels.shape)
print(labels[:15])

(200, 10)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Building a Model

In [3]:
# For a single-input model with 10 classes (categorical classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                3232      
                                                                 
 dense_1 (Dense)             (None, 10)                330       
                                                                 
Total params: 3,562
Trainable params: 3,562
Non-trainable params: 0
_________________________________________________________________


# Compile

In [4]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model, iterating on the data in batches of 32 samples
model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 0s 1ms/step - loss: 1.0417 - accuracy: 0.4950
Epoch 2/10
32/32 [==============================] - 0s 1ms/step - loss: 0.7469 - accuracy: 0.4980
Epoch 3/10
32/32 [==============================] - 0s 2ms/step - loss: 0.7139 - accuracy: 0.5250
Epoch 4/10
32/32 [==============================] - 0s 1ms/step - loss: 0.7023 - accuracy: 0.5360
Epoch 5/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6945 - accuracy: 0.5600
Epoch 6/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6894 - accuracy: 0.5440
Epoch 7/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6787 - accuracy: 0.5740
Epoch 8/10
32/32 [==============================] - 0s 935us/step - loss: 0.6799 - accuracy: 0.5900
Epoch 9/10
32/32 [==============================] - 0s 896us/step - loss: 0.6735 - accuracy: 0.5890
Epoch 10/10
32/32 [==============================] - 0s 871us/step - loss: 0.6669 - accuracy: 0.6040


# Evaluate

In [5]:
score = model.evaluate(test_data, test_labels, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.7370103597640991
Test accuracy: 0.4399999976158142


# Predict

In [16]:
prediction = model.predict(np.random.random((1, 100)))
print(prediction)
print(sum(prediction[0]))
(prediction>0.5)*1

1/1 [==============================] - 0s 36ms/step
[[3.7895727e-01 6.2102890e-01 8.6916702e-07 1.0507757e-06 1.2044217e-06
  2.7734886e-06 8.1544073e-07 6.3211628e-06 4.6012858e-07 3.3380576e-07]]
1.0000000001133174


array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

# Exercise 1
### Develop a multiclass classification model for the following. Populate a dataset 2000 samples where 1500 samples for training, 500 samples for testing. The dimension of each sample is 225. Build a neural network model with 64 nodes in first layer with Relu activation and sigmoid activation function for output layer. Run the model for 10 epochs with batch size of 16 samples. Evaluate the model with test data and print accuracy.

# Exercise 2
### Run the model with different number of epochs such as 10, 15, 20, 25 and compare the accuracies

# Exercise 3
### Run the model with different number of batch sizes such as 2, 4, 8, 16, 32, 64 and compare the accuracies